### ISSUE TITLE
Is the wrong version of the cdms documentation online?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#100]
I have just noticed when looking at the online version of the cdms documention, when looking for **MV2** documentation that **we seem to have the wrong version online**! :(

http://uv-cdat.llnl.gov/documentation/cdms/cdms_2.html#2.9

@chaosphere2112 could you check which pdf documentation you converted? When I look at the above page, it mentions MV (and not MV2 !), and looks very similar to the content of _cdms.pdf_:

_Climate Data Management System - Version 4.0 - November 2003_

What we really want is the content of **cdms5.pdf**

**Climate Data Management System - Version 5.0 - October 2007**

**Comment by chaosphere2112** [comment]
I just found a copy of **cdms5.pdf**; I'll work on porting it over into the site and replace what we have. That CDMS documentation has been a bit sloppy ever since I cleaned it up somewhat from whatever source it was scraped from previously.

**Comment by jypeter** [comment]
Thanks!

**Comment by chaosphere2112** [comment]
I've started working on porting the old CDMS5.pdf manual to SPHINX [here](/UV-CDAT/cdms_manual); I'm hoping to finish by the end of February (fitting it around my other tasks).

**Comment by jypeter** [comment]
Thanks Sam!
