### ISSUE TITLE
tutorials built from iPython notebooks nightly

### ISSUE THREAD

**Issue by mattben** [CDAT/cdat.github.io#117]
we should have a script that pulls all the iPython notebooks from aims4 and auto magically re generates the tutorials page.

**Comment by aashish24** [comment]
👍

**Comment by doutriaux1** [comment]
@mattben I have a script ofr this in the iPython directory

Also @chaosphere2112 mentioned that jekyll should be able to automatically add a div into `tutorials.md`

**Comment by mattben** [comment]
I'll get with @chaosphere2112 and get it implemented on the server
