### ISSUE TITLE
iPython NoteBooks without images should have a default one in Tutorial Section

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat.github.io#123]

**Comment by mattben** [comment]
I can do this, @doutriaux1 is there a good ipython or notebook logo I should use?

**Comment by doutriaux1** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwi8xbytgczQAhVJs1QKHaksCw0QjRwIBw&url=https%3A%2F%2Fipython.org%2Fipython-doc%2F3%2Fwhatsnew%2Fversion0.13.html&psig=AFQjCNEgxXSoaRRSYdhza2TLZ3Jw6nvs-g&ust=1480441724115517

**Comment by doutriaux1** [comment]
or the uv-cdat logo

**Comment by doutriaux1** [comment]
![](http://nbsphinx.readthedocs.io/en/0.2.7/_images/notebook_icon.png)

**Comment by mattben** [comment]
Thank you
