### ISSUE TITLE
Error in Documentation->Getting started

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#128]
@mattben and @chaosphere2112 if you go to the main web site, https://uv-cdat.llnl.gov/index.html, and then select _Getting started_ in the _Documentation_ pull down menu, you get to a wiki page that has instructions for the pre-conda versions of CDAT! I'm not sure that's what you had in mind

https://github.com/UV-CDAT/uvcdat/wiki/Getting-Started

Besides, this wiki page shows the following at the top, which suspiciously looks like some wiki or site generation syntax error
```
title: Getting Started with UV-CDAT
layout: default
```

**Comment by mattben** [comment]
@doutriaux1 should I remove the link complete or have it point to say the gallery? Will anyone re-write the page?

**Comment by jypeter** [comment]
Well, people need a _Getting started_ page, don't they? I guess the minimum change may be to point to the following page

https://github.com/UV-CDAT/uvcdat/wiki/Install

**Comment by jypeter** [comment]
Hmmm, I have just seen that from the top of the gallery

https://uv-cdat.llnl.gov/gallery.html

There is a helpful note _Feeling lost? Check out our Getting Started guide._ that links to a page on the web site that has a very similar (and therefore a bit out-of-date) content to the wiki page

https://uv-cdat.llnl.gov/getting_started.html

**Comment by doutriaux1** [comment]
@mattben i edited the text, can we safely remove the "alyout/title" bits? I"ll let you handle this.
