### ISSUE TITLE
VERY ODD example in the "VCS Functions" part of the online manual

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#130]
@chaosphere2112 @doutriaux1 I have just checked the FIRST example you get when you visit the following link in the vcs documentation: https://uvcdat.llnl.gov/documentation/vcs/vcs-4.html#4.5

You get the following
```
import vcs # import the VCS module
import cdms2 # import CDMS for ingesting data

cdms2.setAutoReshapeMode('on') # needed by CDMS module if

# data is reshaped

f=cdms2.openDataset('example.nc') # open file via the cdms2 module

psl=f.variables['clt'] # get the "psl" variable

data=psl[...] # get the "psl" variable data (Note, data is

# now a Numeric array)

v=vcs.init() # "v" is an instance of the VCS class

# object (constructor)

v.plot(data, variable=psl) # call "plot" function to display the CDMS

# Persistent Array on the VCS Canvas using default settings
```

LOTS of remarks (more than lines in the example):
- _cdms2.setAutoReshapeMode('on')_ **does not exist**. It's not even a function I had ever heard of in previous versions, so it's odd to see it in a beginners' example
- _f=cdms2.openDataset('example.nc')_ is an odd way to open a file. I have always used and appreciated the straightforward: **f=cdms2.open('example.nc')**
- there is a confusion between psl and clt, in _psl=f.variables['clt'] # get the "psl" variable_
- why would you read a variable that way, when the traditional and straightforward way is: **clt = f('clt')**
- what is this _data=psl[...]_? Maybe this is some way of converting a file variable to a transient variable (which is beyond the scope of this **vcs** example) but then you would still get a variable, and not _now a Numeric array)_
- if the example used the old _clt_ data, it should show how to download and use the test data files, rather than opening a bogus _example.nc_
- _v=vcs.init() # "v" is an instance of the VCS class_: hmm, it seems odd to use *v* as a name for a canvas (that's more for a variable), when traditional examples rather use *x* as the canvas name! Well, a bit later in the same web page, you have in the same example: _v = vcs.init()_ immediately followed by _t = x.createtemplate('new')_. And just before, there is yet another strange way to read a variable: _s = f.getslab(`psl')_
- on the init line, a more appropriate comment (if you want to teach the beginning user something) would be: _create a vcs 'canvas' (graphics window)_ 
- _v.plot(data, variable=psl) # call "plot" function to display the CDMS Persistent Array_? We like vcs because it has powerful defaults! And what is thing with using both _data_ and _psl_??? This should be: _v.plot(psl) # Plot the psl variables on the canvas, using the default settings_

**Comment by doutriaux1** [comment]
@jypeter this has been converted directly from the 90s documentation. Thanks for pointing it out. I'll take care of it.

**Comment by jypeter** [comment]
OK, old bugs and inconsistencies! :( I thought maybe that had been introduced by someone who was not completely familiar with the package.

Maybe there should be some warning at the top of the documentation pages saying that they have been converted from the old documentation and that the users should first check the gallery, look at the notebooks, and use the builtin help to access the docstrings with **help(cdms2.open)** and **pydoc -g**
