### ISSUE TITLE
Slight error in the "Walkthrough of each attribute of Boxfill" tutorial

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#131]
I have had a **quick** look at the **quite nice** boxfill tutorial: https://uvcdat.llnl.gov/iPython/boxfill/boxfill.html

Between the **box.legend** and **box.ext_1 and box.ext_2** sections, you may want to get rid of the following. Looks like a notebook cell may have been re-executed _out of sequence_ (or whatever the name is for this kind of thing) and generated an error. That's one of the reasons I don't like notebooks
```
---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

<ipython-input-1-3613f8fddaf0> in <module>()
----> 1 box.legend = {15: "This is a point", 30: "This is another point", 60: "One more"}
      2 x.clear()
      3 x.plot(s, box, template)


NameError: name 'box' is not defined
```

**Comment by doutriaux1** [comment]
@chaosphere2112 do you mind regenerating the notebook? Thanks.
