### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by mattben** [CDAT/cdat.github.io#134]
This issue may be open on the uvcdat repo but I just want to double check.

Is there anything I'll need to do to the site when @doutriaux1 creates a new release notes?

**Comment by chaosphere2112** [comment]
Yeah; you'll need to add an entry to `releases/index.md` pointing at the release and the changelog (which gets inserted at the top of `changelog.md` with an anchor tag using the version number)

**Comment by mattben** [comment]
Charles creates and pushes the release notes.
