### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mattben** [CDAT/cdat.github.io#135]
Wrong repo….

https://uvcdat.llnl.gov/docs/index.html

- [ ] Building Documentation (html, pdf)
- [ ] Doc Strings
- [ ] Running Doc Tests
- [ ] Writing / Editing Doc Tests
- [ ] Brain Dump

**Comment by chaosphere2112** [comment]
1. Building Documentation:
    - The immediate process is pretty easy:
         ```
         cd vcs/docs
         make html
         make pdf
         ```
        These will output to `vcs/docs/_build/html` and `vcs/docs/_build/latex` respectively.
    - Eventually should work on getting this done as part of the tagging process (and possibly maintaining a nightly version of the docs to go with the builds pushed to the nightly label)
2. Doc Strings:
    - These are automatically imported by the documentation. They're formatted using [Restructured Text](http://docutils.sourceforge.net/docs/user/rst/quickref.html), not markdown (though they look very similar) and include commands for [Sphinx](http://www.sphinx-doc.org/en/stable/), the documentation engine that we're using.
3. Doc Tests:
   - @doutriaux1 is working on integrating these with the test suite, so they should be automatically run and basically not your problem. The VCS developers should be adding them as they add new functionality, in theory, and at a minimum will be keeping them up to date so the build doesn't break. Guides to doctests: https://docs.python.org/2.7/library/doctest.html
4. Brain dump:
    - I don't actually have a lot to dump for this project; it's been pretty stable. We need to look into getting the jupyter notebook stuff handled automatically as part of the build process (I'd recommend basically just having a daily cron that pulls down a separate repo, builds the html, and dumps it into the _site directory to be served).

**Comment by mattben** [comment]
Done(ish) and Copy of Sams notes moved to https://acme-climate.atlassian.net/wiki/spaces/AIMS/pages/560333513/Deploy+our+sites (user account required)
