### ISSUE TITLE
Installation page inconsistency

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#157]
@mattben @doutriaux1 When you are on the home page of the site, https://cdat.llnl.gov/, you have the following sentence and link: "you can look into getting our application [installed](https://cdat.llnl.gov/installing.html)", where the link points to: A) https://cdat.llnl.gov/installing.html

Yet, when you click on the _Installing_ button at the top of the page, the link is B) https://github.com/CDAT/uvcdat/wiki/install

I think you should use A) in both cases

**Comment by doutriaux1** [comment]
@jypeter actually B) iswhat we want. @mauzey1 this would be a good one for you to start understanding the VCS website.
@jypeter FYI @mattben left our group and @mauzey1 will be taking over.

**Comment by jypeter** [comment]
Oh, OK. Well, there is a link to B) (and additional information) from A), that's why I thought it seemed better, but it's your call

Welcome @mauzey1 !

**Comment by jypeter** [comment]
@doutriaux1 I have followed the outdated A) link again! Can somebody fix the home page?

**Comment by jypeter** [comment]
@doutriaux1 I'm a bit confused again, because I have started following the instructions on

B) https://github.com/CDAT/cdat/wiki/install

And then I branched to the Win10+WSL page that I was interested in, and in the end the Win10+WSL page sends you to

C) https://github.com/CDAT/cdat/wiki/Install-using-Anaconda

B) and C) are very (but not quite) similar, and the duplication is confusing. Can somebody sort that out and keep a unique page?

**Comment by davis278** [comment]
The two installation pages you mention above have been edited to eliminate overlapping/conflicting instructions. The Install-using-Anaconda page was edited and renamed to https://github.com/CDAT/cdat/wiki/Additional-Installation-Configurations. Thanks for your input @jypeter.
