### ISSUE TITLE
Add documentation for EzTemplate

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#159]
The only place where Google can find a reference to the nice EzTemplate module is the [Polar Plots demo](https://cdat.llnl.gov/Jupyter/PolarPlots/PolarPlots.html#clock), where the module is used, with no users' manual on the web site!

It would be useful to have some form of https://github.com/CDAT/cdat-old-site/blob/master/eztemplate.md back on the current web site, with some links to find it easily

**Comment by doutriaux1** [comment]
@jypeter it used to be in the gallery. I will revive it today as a notebook.

**Comment by doutriaux1** [comment]
@jypeter see: https://github.com/CDAT/vcsaddons/blob/cleanup_eztemplates/Doc/Jupyter/Ez%20Templates.ipynb and #158

**Comment by doutriaux1** [comment]
Should be online at https://cdat.llnl.gov shortly

**Comment by jypeter** [comment]
Closing this, because I can indeed see the notebook in the tutorials
