### ISSUE TITLE
Full name of CDAT not displayed correctly on home page?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#173]
@doutriaux1 is it normal that, on the [CDAT home page](https://cdat.llnl.gov/), the full name of CDAT is on 2 lines, _Community_ on one line, and then _Data Analysis Tools_ on the next line with a **smaller** font ?

**Comment by doutriaux1** [comment]
Nope. @davis278 do you mind approving the PR at: https://github.com/CDAT/cdat.github.io/pull/174

**Comment by davis278** [comment]
This issue has been resolved so closing the issue.
