### ISSUE TITLE
TWO different views of getting_started

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#179]
Some googling sent me to a nice looking _Getting started_ page

A) https://cdat.llnl.gov/getting_started.html

But when I'm on A) and I click on "Getting started" from the Documentation pull-down menu, I get to

B) https://github.com/CDAT/cdat/wiki/Getting-Started

Are A) and B) the same thing? Can you set-up things so that when you are on the main web site, you mostly get pages from cdat.llnl.gov rather than pages from the wiki on github.com ? As I've already said in other issues, this can be quite confusing when navigating and searching information

**Comment by davis278** [comment]
Thanks @jypeter. I've created a pull request (https://github.com/CDAT/cdat.github.io/pull/182) which should fix the issue, so hopefully it will be deployed soon.

**Comment by davis278** [comment]
Closing issue since pull request #182 fixed the issue.
