### ISSUE TITLE
Replace occurences of "cdat8" with "cdat81" on Install page?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#187]
@doutriaux1 your mail mentions
`conda create -n cdat81  -c cdat/label/v81 -c conda-forge cdat`

But the Install pages ([Install](https://github.com/CDAT/cdat/wiki/install) and [Install using Anaconda](https://github.com/CDAT/cdat/wiki/Install-using-Anaconda) are still installing in a `cdat8` environment
```
conda create -n cdat8 -c cdat/label/v81 -c conda-forge -c cdat python=3.6 cdat
conda activate cdat8
```

Should you **replace cdat8 with cdat81** on those pages? When someone check these 2 pages, you can decide if you can merge them and solve #157

**Comment by doutriaux1** [comment]
@jypeter the `-n` option is the name of your conda env it can be whatever you want. `-n jyp` if you want, as long as the `create` and `activate` lines are consistent it really doesn't matter. But thanks for spotting it. @davis278 I will let you decide if we want to update the pages or not.

**Comment by jypeter** [comment]
I know you can use whatever name you want. Just thought you maybe wanted to stay consistent

If I understood your mail correctly, @davis278 can also remove all the occurrences of `-c cdat` on the _create_ lines

**Comment by davis278** [comment]
This issue has been resolved: -c cdat occurrences on the create lines have been removed and references to the environment as cdat8 have now been changed to cdat81.
