### ISSUE TITLE
Broken CDAT links on main PCMDI Software Portal page

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#31]
Hi guys,

Happy new year, with lots of UV-CDAT breakthroughs! :)

I was looking for CMOR related information, and I discovered that CDAT is still mentioned at the top of the software portal (as it should be). Unfortunately, all the links are broken, so you may want to add a link to the correct UV-CDAT page

http://www2-pcmdi.llnl.gov/

The 'navigation' links on the left are still good, with potentially useful information (eg the old newsletters) and the main cdat page does provide  a link to uvcdat

http://www2-pcmdi.llnl.gov/cdat

There are still lots of tips and tricks from the old CDAT that apply to uvcdat, so you may want to include links to
- http://www2-pcmdi.llnl.gov/cdat/tips_and_tricks
- and   http://www2-pcmdi.llnl.gov/Newsletter
- and   [other old useful pages?]

in http://uvcdat.llnl.gov/ -> Documentation -> "Old documents" or something like that

**Comment by mattben** [comment]
all pcmdi web sites are under major construction and will all be under pcmdi.llnl.gov very soon.

**Comment by doutriaux1** [comment]
@mattben let's leave it open until it's fixed for real.
