### ISSUE TITLE
Things to do about the cdat-discussion list ?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#32]
I have just re-discovered that, contrary to _uvcdat-support_, the content of **cdat-discussion** has correctly been archived and is still accessible

http://sourceforge.net/p/cdat/mailman/cdat-discussion/

Maybe somebody should do the following about cdat-discussion (when possible):
- Make sure that nobody else can subscribe to the list, since it is discontinued
- Send a last mail to the list reminding people that they should use uvcdat-support instead, and make sure that no new mail can be sent to the list. The most recent mail like that I found was sent by Charles in April... 2013 (http://sourceforge.net/p/cdat/mailman/message/30698923/)! And the most recent mail sent to the list is dated December 2014
- Add a link from uvcdat web site to the archives
- Try to index the old archives, as specified in #15

**Comment by mattben** [comment]
Is any of that useful information at this point? @doutriaux1

**Comment by doutriaux1** [comment]
We're trying to drop the cdat-discussion as much as possible. But we could definitely add a link to it burried at the bottom of a page :wink:
