### ISSUE TITLE
The vcs documentation lists deprecated functions and misses new ones

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#43]
It would be nice to update http://uvcdat.llnl.gov/documentation/vcs/vcs-11.html#pgfId-912045
- remove deprecated functions like https://github.com/UV-CDAT/uvcdat/issues/1065
- add new _slightly_ useful ones like x.interact(), x.setbgoutputdimensions() and probably others

Good luck @chaosphere2112  and @mattben !

**Comment by chaosphere2112** [comment]
Yeah, that's definitely a good idea. I'll take a pass through that page and remove everything that is deprecated, and I'll definitely add `interact()` and `setbgoutputdimensions()`
