### ISSUE TITLE
Add a page or tutorial dedicated to generating vcs output

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#44]
I have spent some time rediscovering that you have to use _setbgoutputdimensions_ in order to get a bigger png file, and that I had already asked the question in https://github.com/UV-CDAT/uvcdat/issues/470! :-(

I think it would be **very useful** to have a specific page/tutorial describing the different canvas output formats, how to generate high resolution output, and how to use successfully the offline (bg=1) mode

@doutriaux1 btw, can you now use bg=1 on a headless display?

**Comment by chaosphere2112** [comment]
I agree; I think a page on formatting your output in general would probably be very useful (template attributes, `priority`, generating images, etc.). I'll try and book some time to do that soon.

**Comment by mccoy20** [comment]
Hi Sam,

It might be nice to also add plot layout tips from some old tips for the cdat, I once wrote, see here

http://www2-pcmdi.llnl.gov/Newsletter/Vol2/techTips.html
http://www2-pcmdi.llnl.gov/Newsletter/Vol2/images/template_asd3.jpg

Here are some other tech tips from newsletters
http://www2-pcmdi.llnl.gov/Newsletter/Vol5/archive.html

Greetings,
Renata

**Comment by chaosphere2112** [comment]
Awesome! Thanks Renata! I'll make sure to get this content integrated.

-Sam

**Comment by jypeter** [comment]
Indeed, there were some good tips in the old newsletters, as I mentionned in https://github.com/UV-CDAT/uvcdat-site/issues/31 :)

There is a lot to explain about the output, and it's not very easy. I have never mastered everything
* the **available output formats**, and do we have a truly clean vector output format now? Last time I checked (years ago, I admit), the vector isofills were just zones filled with lots of horizontal lines, when you looked up close
* the **normalized coordinates** of the canvas that you have to know about in order to alter the templates
* the **canvas size**: default size and how to change that
* the **canvas orientation**: portrait or landscape. And I wonder what happens if the orientation is landscape by default, but you manually specify a size that is actually portrait
* the fact that the default **canvas size ratio** is based on *US Letter* and that probably lots of ratios are internally based on that
* how does everything affect the **actual size** of the output plots?
* the **size of the plots on the canvas**, and the **ratio='autot'** parameter of x.plot
* and I remember a discussion about transparency and **background color**
* plotting things in **background/offline/headless** mode with **bg=1**
* etc...
