### ISSUE TITLE
DV3D Camera parameters

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#47]
@chaosphere2112 and @ThomasMaxwell 

I'm not familiar with camera positioning coordinates. Could you give some explanations in Chapter 12 about the Position/ViewUp/FocalPoint parameters? Maybe these are standard parameters and there is already a wiki or some page that could be linked to

**Comment by ThomasMaxwell** [comment]
These terms are in accordance with standard usage.   Position denotes the position of the camera.  FocalPoint is a remote position that determines the direction that the camera is pointing.  ViewUp is a vector that denotes the “Up” direction of the camera.

— Tom

**Comment by jypeter** [comment]
Well, I have tried to some more information on google in even dug up my old computer graphics text book (Computer Graphics by Foley, van Dam et al), but I have not been able to find a nice plot that would give me a quick grasp of these parameters. It would be nice if there was such a thing.

@aashish24 , is there some 3D positioningfor dummies plot  on the VTK site?

Meanwhile, I will just move my plot interactively :)

**Comment by chaosphere2112** [comment]
@jypeter I've written a small script that you can use to figure out how the camera parameters work; unfortunately, it's dependent on a PR that I've just submitted. The PR is UV-CDAT/uvcdat#1184 , if you want to try using it with the script:

```python
import vcs, cdms2
x = vcs.init()
f = cdms2.open( vcs.prefix + "/sample_data/geos5-sample.nc" )
v = f["uwnd"]
dv3d = vcs.get3d_scalar()
dv3d.ToggleVolumePlot = vcs.on
dv3d.ToggleSurfacePlot = vcs.on
dv3d.IsosurfaceValue = 31.0
dv3d.Camera = {
    'Position': (-161, -171, 279),
    'ViewUp': (.29, 0.67, 0.68),
    'FocalPoint': (146.7, 8.5, -28.6)
}

x.plot( v, dv3d )

message = "Enter (p|v|f) (x|y|z) # or exit to adjust camera or exit: "

camera = {
    'Position': (-161, -171, 279),
    'ViewUp': (.29, 0.67, 0.68),
    'FocalPoint': (146.7, 8.5, -28.6)
}

cam_map = {
    "p": "Position",
    "v": "ViewUp",
    "f": "FocalPoint",
}

def process_input(in_str):
    trimmed = in_str.strip()
    parts = trimmed.split()
    if len(parts) < 3:
        print "Invalid input."
        return False

    if parts[0] not in cam_map:
        print "Camera component invalid: expected 'p', 'v', or 'f', got %s" % parts[0]
        return False
    
    data = camera[cam_map[parts[0]]]

    if parts[1] not in ("x", "y", "z"):
        print "Coordinate component invalid: expected 'x', 'y', or 'z', got %s" % parts[1]
        return False

    try:
        value = float(parts[2])
    except ValueError:
        print "Value invalid: expected a float, got %s" % parts[2]
        return False

    if parts[1] == "x":
        data = value, data[1], data[2]
    elif parts[1] == "y":
        data = data[0], value, data[2]
    elif parts[2] == "z":
        data = data[0], data[1], value

    camera[cam_map[parts[0]]] = data
    return True

in_str = raw_input(message)
while in_str not in ("exit", ""):
    if process_input(in_str):
        dv3d.Camera = camera
        x.plot(v, dv3d)
    in_str = raw_input(message)
```
