### ISSUE TITLE
Printing DV3D parameters, and other shortcuts

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#48]
- I think @ThomasMaxwell mentioned during the F2F that there was a keyboard shortcut to print the current parameters (Camera position? Others?) to the shell. What is it?
-  Could @chaosphere2112 list all the available DV3D shortcuts and mouse/keyboard combinations in Chapter 12? That could go to a dedicated section ("Interacting with the 3D plot window"?). I think I have just found _Left-click in window and drag to rotate. Right-click and drag to zoom/pan. Shift-Left-click and drag to translate_ in the _Camera_ parameter description

Thanks!

**Comment by ThomasMaxwell** [comment]
Pressing the ‘p’ key when the plot has focus prints all the parameters to the shell.  These key press shortcuts are not documented because they are intended for developers and testers.

**Comment by jypeter** [comment]
On the contrary, I think this is very useful if you want to play around interactively, and then create a script that will put you directly in the state you want! Especially if you don't know how the camera parameters (#47)  work...

Do you also have a key that will reset the parameters to a default state? Right now, if I move too many things around and I want to go back to an initial clean state, all I can do is quit and restart my script

**Comment by ThomasMaxwell** [comment]
The “save script” button in the uvcdat gui does what you are asking.   To make this feature available from a script we would need to add this functionality to the vcs api.  However, for testers, if you press the ’t’ key a ctest definition capturing the current state is written to stdout.   This can be run as a script.
