### ISSUE TITLE
Youtube videos linked not available

### ISSUE THREAD

**Issue by durack1** [CDAT/cdat.github.io#75]
The youtube videos linked at http://uvcdat.llnl.gov/animations.html are not available - these links should be updated (if available).

**Comment by chaosphere2112** [comment]
Probably going to have to talk to the authors of those papers; I saw @doutriaux1 listed on one of them. Any idea where we could find those animations, Charles?

**Comment by doutriaux1** [comment]
I will chase them down. Thanks for spotting this.

**Comment by chaosphere2112** [comment]
:+1:

**Comment by durack1** [comment]
@doutriaux1 I know there are many more of these - would be good to collect them all in one place - this page seems appropriate..

**Comment by aashish24** [comment]
@durack1 +1

**Comment by durack1** [comment]
@chaosphere2112 to be honest it would also be nice if there was a placeholder still image, or the youtube window embedded too - if we have candy to show may as well show candy.. I assume you can embed youtube links and just have them not play until toggled..?

**Comment by chaosphere2112** [comment]
@durack1 Yup, that's quite doable. Just need to have the videos.

**Comment by durack1** [comment]
@chaosphere2112 this might help: https://www.youtube.com/user/llnlaimsgroup

**Comment by durack1** [comment]
and another PCMDI related one: https://www.youtube.com/watch?v=3jbrfQZwoHA

**Comment by durack1** [comment]
@williams13 also has a video on his climate game from memory too..?

**Comment by mattben** [comment]
the game is still up https://climatesim.llnl.gov/

**Comment by durack1** [comment]
@doutriaux1 @chaosphere2112 @mattben any luck locating these.. Some lab managers have been asking me about providing them some animations of climate models, it would be great to provide them something that's been generated in-house.. Otherwise I'll fall back to animations that Australian and French collaborators have provided..

What's the chance of a quick turnaround on some hi-res animations??

**Comment by durack1** [comment]
Here are some more, and files! http://climate.llnl.gov/animations.html

**Comment by mattben** [comment]
https://uvcdat.llnl.gov/mov/Exploratory-DiagnosticsTree.mov
https://uvcdat.llnl.gov/mov/GO-ESSP%20Tech%20Presentation%20ESGF%20-%20IdEA%209-2-14 8.00%20AM.mov
https://uvcdat.llnl.gov/mov/h264.mp4
https://uvcdat.llnl.gov/mov/LLNL_acme-web-fe.mov
https://uvcdat.llnl.gov/mov/mp2_high.mp4
https://uvcdat.llnl.gov/mov/mp2_low.mp4
https://uvcdat.llnl.gov/mov/orbit.mov
https://uvcdat.llnl.gov/mov/ORNLExploratoryCorrelationHeatmap.mov
https://uvcdat.llnl.gov/mov/ORNLExploratoryGeoInteractionPlotsCLMDataset.mov
https://uvcdat.llnl.gov/mov/ORNLExploratoryParallelCoordinates.mov
https://uvcdat.llnl.gov/mov/UVCDAT_Departures_MM_annotated4.mp4
https://uvcdat.llnl.gov/mov/UVCDAT_error_tf-ta_anno4.mp4
https://uvcdat.llnl.gov/mov/UV-CDAT_Live.mov

**Comment by durack1** [comment]
@mattben the original linked page https://uvcdat.llnl.gov/animations.html still doesn't have anything showing

**Comment by mattben** [comment]
What page do you see that link on?

https://uvcdat.llnl.gov/tutorials.html?

**Comment by durack1** [comment]
@mattben it looks like it's been lost off the new site nav.. I wonder what other goodies have been lost..?

**Comment by durack1** [comment]
@mattben where are the videos in https://github.com/UV-CDAT/uvcdat-site/issues/75#issuecomment-286460182 linked off? I can't seem to find them in the new nav
