### ISSUE TITLE
The web site does not mention udunits

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#80]
I have experimented a bit with udunits2, after experimenting with the units page mentioned in the CF mailing list: https://www.cicsnc.org/pub/jbiard/Udunits2Tables.html 

It could be useful to mention that **udunits2** is bundled with UV-CDAT, in the http://uvcdat.llnl.gov/documentation/utilities/utilities.html section

```
>>> import genutil
>>> s = genutil.udunits(1, 'sverdrup')
>>> 1.5 * s
udunits(1.5,"sverdrup")
>>> s.to('m3 s-1')
udunits(1000000.0,"m3 s-1")
>>> # Some really dummy conversion
>>> s.to('stokes US_survey_foot')
udunits(32808333333.3,"stokes US_survey_foot")
```

I have reported a slight error in the docstring in https://github.com/UV-CDAT/uvcdat/issues/1399

**Comment by mattben** [comment]
@jypeter  is this related to #81? @chaosphere2112 @doutriaux1 ideas?

**Comment by doutriaux1** [comment]
yep same thing, the doc we used is old, lots has been added since, but doc never updated...

**Comment by jypeter** [comment]
Indeed, same kind of problem. You want people to easily find what makes CDAT more interesting than anaconda or canopy for the climate community!

And of course make it easy to install ;-)

**Comment by doutriaux1** [comment]
@jypeter actually that's right, we should have a page describing our value added compared to other distributions.

**Comment by jypeter** [comment]
I think I suggested that when I was at PCMDI last December:
- say less about the sponsors and the governance: good, it has moved *out of way* in the Project information at the bottom of the page!
- say more about CDAT specifics and why climate scientists should use it: maybe try to do something more sexy in the *The UV-CDAT Project* part of the home page. Say that it has been developed by climate scientists for climate scientists during several IPCC reports, blablah, and that it's bundled with the usual suspects expected by data scientists (numpy, blahblah), plus specific packages. And link to a page with a detailed list (at least the page on the github wiki, but more up-to-date)

**Comment by chaosphere2112** [comment]
I have a restructuring of the documentation on the horizon as something I want to work on, but it's going to be a ways out. If someone wants to write up a blurb on udunits2, I'll happily add it to the utilities document. Also, I've not used the alternatives to UV-CDAT, so I'm going to need someone else to list what it is that we provide that competing software does not.

**Comment by jypeter** [comment]
UV-CDAT is made in CA, so it must be a cool product! ;) The Beach Boys recommend using UV-CDAT (round, round, I get around in the documentation). I think it's really getting too hot in my office

**Comment by chaosphere2112** [comment]
@jypeter Sounds like :wink:
