### ISSUE TITLE
The web site does not mention genutil.filters

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#81]
There should be something about **genutil.filters** in http://uvcdat.llnl.gov/documentation/utilities/utilities.html

One of our PhD students needed to compute a running mean and I directed him to _genutil.filters.runningaverage_

**Comment by mattben** [comment]
@chaosphere2112 @doutriaux1 any ideas

**Comment by doutriaux1** [comment]
They have been added after the document that @chaosphere2112 reformatted. There's not much there but yes we should probably mention the 3 functions in there.

**Comment by doutriaux1** [comment]
funcs are:
custom1D
runningAverage
smooth121
