### ISSUE TITLE
Obsolete http://uv-cdat.github.io/cdat-site/

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#85]
@chaosphere2112 I have followed the **Old CDAT tutorials** link from the _SOFTWARE_ pull-down menu of http://www-pcmdi.llnl.gov, and I found http://uv-cdat.github.io/cdat-site/ !

Maybe this should be completely removed, since this seems to have been meant as a temporary thing?

**Comment by doutriaux1** [comment]
@chaosphere2112 @mattben are all of these on uvcdat site now?

**Comment by mattben** [comment]
I'm not sure I understand the issues. But  http://uv-cdat.github.io/cdat-site/  is the re-write of that content and now where every you click to it, it pulls you to that site. Its hosted on github heres the actually url http://uv-cdat.github.io/cdat-site/

**Comment by doutriaux1** [comment]
The question I guess did we move all of that content one way or another to the uvcdat site.

**Comment by doutriaux1** [comment]
hum... I merged master into this and tried. I get this:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=3937043
Not sure why. The version does say 2.2.0rc1... Maybe i will try rebasing rather than merging..

**Comment by jypeter** [comment]
@mattben when I  look at http://uv-cdat.github.io/cdat-site/, it seems to be some temporary port of the old site, with lots of dead links:
* if you click on the  **vcs link**, you get an old version  with no CSS
 * old: http://www-pcmdi.llnl.gov/software/cdat/support/vcs/vcs.html
 * new: http://uv-cdat.llnl.gov/documentation/vcs/vcs.html 
* if you click on *cdms*, *cdutil*, etc... you just get dead links

This CDAT page is NOT the UV-CDAT page!!

It seems to me that this *site/page* should either be removed because you do not need it any more (eg you have ported everything), or you should add some filters so that people from outside PCMDI can't access it. But it probably **should not be accessible from a pull-down menu from the main PCMDI site**. I have attached below a screenshot of the page I'm talking about, in case we are not seeing the same thing

![obsolete_cdat_page](https://cloud.githubusercontent.com/assets/2785573/9060102/f71634c8-3ab0-11e5-9474-eede00e30558.png)

**Comment by mattben** [comment]
I'm sure thats a mess, it was scavenged and put back together. @doutriaux1 do we need to get an intern to start putting this back together again? Or is @jypeter the only one who finds this things?

**Comment by chaosphere2112** [comment]
@mattben I think the only thing that needs to be done is to somehow remove the link to the site from the PCMDI site (and maybe point that at http://uvcdat.llnl.gov). Is that a doable thing?

**Comment by doutriaux1** [comment]
@mattben I don't know if we need to rebuild the site but we DID lose a bunch of things, for eample today I couldn't find any of my links to the vcsaddons tutorials that where "Somewhere" before.

**Comment by mattben** [comment]
@chaosphere2112 - yes I can change the links on the PCMDI site. @jypeter is this the correct answer? @doutriaux1 when you say somewhere what does that mean? I'll look through the repos and branches for them as well.

**Comment by doutriaux1** [comment]
@mattben "somewhere" means way back when it was hosted on rainbow before we move anything to github. Like medieval times...

**Comment by jypeter** [comment]
* @doutriaux1 I have found a reference to *vcsaddons* in one of your old tutorials (*CDAT_Refresher_2010.pdf*). But I remember a web page where you explained how to easily create templates for having lots of plots on the same page. It would be **very useful** to have that back online. I have found it on the wayback machine!!!! \o/ https://web.archive.org/web/20130217183508/http://www2-pcmdi.llnl.gov/cdat/contrib/eztemplate
 * @mattben and @chaosphere2112 and other *young* people at PCMDI can probably make good use of https://archive.org/web/ to examine information and pages that date from before their time

* http://www-pcmdi.llnl.gov/ page: remove *Old CDAT tutorials* from the *Software* pull-down menu, because it leads to an out-of-date page. Or ask @doutriaux1 or whoever decides what should be on the PCMDI main page
* http://uv-cdat.github.io/cdat-site/ page: you can probably shred this page. The only working link is to a an old version of the vcs documentation, and @chaosphere2112 has made an nicer one available in http://uv-cdat.llnl.gov/documentation/vcs/vcs.html

**Comment by doutriaux1** [comment]
@chaosphere2112 the eztemplate example actually DID show how to use it in vcs. I knew I did that it was just commented out. We should take this page as is and tick it in tutorials section. @jypeter this page is now kindda-sorta reimplemented in the gallery.

**Comment by doutriaux1** [comment]
@chaosphere2112 @mattben @williams13 most of the newsletter should be reformatted and put into the tutorials section as well. Looking at them I'm sort of wondering how come we lost some of these cool features from 2008... :cry:
