### ISSUE TITLE
Add arrows to navigate the documentation?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#86]
I was looking at the documentation and wanted to navigate to other pages of the documentation, because I can't search the uv-cdat site (and the documentation) when the Search is still disabled

I have noticed that there are no buttons (or _breadcrumbs_ or simillar navigation helpers) at the top/bottom of the documentation pages to easily go to:
- previous page
- next page
- home, table of content

**Comment by jypeter** [comment]
My mistake! I have navigated to the very bottom of one of the doc pages and found the links I was requesting!

So the issue is more:
* Add `Previous | Table of Contents | Next` at the top of the pages
* Use a bigger font

**Comment by chaosphere2112** [comment]
I was just about to post a screen shot :smile: 

I'll make sure the revised template for the documentation sticks larger navigation links and puts them on the top as well as the bottom.

**Comment by jypeter** [comment]
Thanks!
