### ISSUE TITLE
Add Charles old tutorials to the Tutorials' page?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#87]
I have just looked at http://uv-cdat.llnl.gov/tutorials.html and I think it would be very useful to put there some of the old tutorials:
- Unlocking_CDATs_Best_Kept_Secrets.pdf
- CDAT_Refresher_2010.pdf
- vcs-2004-tutorial.pdf
- Charles probably has other pdf that I don't know

Trouble is that some of the content may be out of date. But it's still very good and probably more useful for new users than the _raw_ original documentation. It's a bit like the difference between a user's manual and a reference manual

**Comment by chaosphere2112** [comment]
:+1: I'll take a pass through those and update them on my next web sprint.

**Comment by doutriaux1** [comment]
@jypeter @chaosphere2112 that's always been the biggest issue with UV-CDAT although there IS "some" documentation for most things. It has always been nearly impossible to find... And we keep moving around and reorganizing it... So that in the end nobody knows exactly where anything is...

**Comment by jypeter** [comment]
It can be quite a challenge! That's why I save these files in a special directory, when I find one ;)
