### ISSUE TITLE
Document the regridding capabilities of UV-CDAT

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#88]
Is there a place where _regridding with UV-CDAT_ is documented? That's one of the assets of UV-CDAT over other python distributions, but even I usually don't use it because of the lack of documentation (and the fact that it can use a lot of RAM...). I usually end up using `regrid2.Horizontal`

All I have is:
- A short presentation: http://earthsystemcog.org/site_media/projects/esmf_exec2014/pres_1406_doutriaux.pptx
- A pdf file: PletzerAMSJan2012.pdf (https://ams.confex.com/ams/92Annual/webprogram/Handout/Paper203234/PletzerAMSJan2012.pdf)
- A link: https://ice.txcorp.com/trac/modave/wiki/regrid
- Another link: https://earthsystemcog.org/projects/esmp/
- The nice examples made by @stefraynaud when using vacumm+UV-CDAT: http://www.ifremer.fr/vacumm/gallery.html

After listing all this, I realize that there is more documentation than I thought but:
- it's not accessible from the UV-CDAT site
- it's not easy to start with
- it's scary for people traumatized by irregular grids (like me)

**Comment by chaosphere2112** [comment]
@doutriaux1 Dunno, is there anything more than http://uvcdat.llnl.gov/documentation/cdms/cdms_1.html#1.10 ?

**Comment by chaosphere2112** [comment]
Regardless, I can gather up some of that stuff and get it on the site.

**Comment by doutriaux1** [comment]
@chaosphere2112 yes that would be awesome to gather all this under tutorials->regridding
