### ISSUE TITLE
Help people acknowledge UV-CDAT

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#89]
Is there a place on the site where you tell how people should acknowledge UV-CDAT? I think I mentioned it to @chaosphere2112 in December but either it's not on the site, or it's not where I'm looking for it

It could be a section at the bottom of http://uv-cdat.llnl.gov/installing.html, and you could also have a link to this new section from http://uv-cdat.llnl.gov/contact.html

And remind people to send you some links and pictures of what they have done

**Comment by chaosphere2112** [comment]
Good idea! I'll draft some text for this and run it by Dean and Renata.

**Comment by doutriaux1** [comment]
well... https://github.com/UV-CDAT/uvcdat/blob/master/README.md contains a DOI...

**Comment by jypeter** [comment]
But that's just a DOI for 2.2.0

Of course, it would be nice to have a GMD (http://www.geoscientific-model-development.net/index.html) paper to reference. I have just searched GMD, and there are some papers mentioning CDAT!

http://www.geosci-model-dev.net/full_text_search.html?x=5&y=7&q=cdat
