### ISSUE TITLE
Add a page for listing packages using UV-CDAT?

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#90]
When mentioning @stefraynaud **vacumm package** in #88, I have realized that maybe there should be a page listing packages that use UV-CDAT. But I don't know where it should be on the site (a new subsection of _Documentation_?). Something basically stating: _hey, we are not alone! Other people use UV-CDAT_.

Maybe also list some _UV-CDAT success stories_ as well! And remind people to acknowledge UV-CDAT (#89) and send you some references of the accomplishments 

The link for vacumm is: http://www.ifremer.fr/vacumm/index.html

**Comment by chaosphere2112** [comment]
@doutriaux1 Do we have any notion of what all uses UV-CDAT out there?

**Comment by doutriaux1** [comment]
@jypeter @chaosphere2112 when you build UV-CDAT a manifest is produced that tells you exactly what will be built and which version. @aashish24 is supposed to finish up the tables at: https://github.com/UV-CDAT/uvcdat/wiki/Install-from-source-command-line-options
But I remember having this information somewhere else, but of course can't find it. It might have been for CDAT only...

**Comment by doutriaux1** [comment]
the file name is build_info.txt
here an example form yesterday using -DCDAT_BUILD_GRAPHICS=OFF
```
pkgconfig 0.28.0 http://uv-cdat.llnl.gov/cdat/resources/pkg-config-0.28.tar.gz
readline 6.2 http://uv-cdat.llnl.gov/cdat/resources/readline-6.2.tar.gz 67948acb2ca081f23359d0256e9a271c
Python 2.7.10 http://uv-cdat.llnl.gov/cdat/resources/Python-2.7.10.tgz d7547558fd673bd9d38e2108c6b42521
NUMPY 1.9.0 http://uv-cdat.llnl.gov/cdat/resources/numpy-1.9.0.tar.gz a93dfc447f3ef749b31447084839930b
setuptools 17.1.1 http://uv-cdat.llnl.gov/cdat/resources/setuptools-17.1.1.tar.gz 7edec6cc30aca5518fa9bad42ff0179b
pip 7.1.0 http://uv-cdat.llnl.gov/cdat/resources/pip-7.1.0.tar.gz d935ee9146074b1d3f26c5f0acfd120e
SIX 1.9.0 http://uv-cdat.llnl.gov/cdat/resources/six-1.9.0.tar.gz 476881ef4012262dfc8adc645ee786c4
DATEUTILS 2.2 http://uv-cdat.llnl.gov/cdat/resources/python-dateutil-2.2.tar.gz c1f654d0ff7e33999380a8ba9783fd5c
PYPARSING 2.0.2 http://uv-cdat.llnl.gov/cdat/resources/pyparsing-2.0.2.tar.gz b170c5d153d190df1a536988d88e95c1
Matplotlib 1.4.3 http://uv-cdat.llnl.gov/cdat/resources/matplotlib-1.4.3.tar.gz f1bb5e2317cceed593119fad2071e236
GEOS 3.3.5 http://uv-cdat.llnl.gov/cdat/resources/geos-3.3.5.tar.bz2 2ba61afb7fe2c5ddf642d82d7b16e75b
basemap 1.0.5 http://uv-cdat.llnl.gov/cdat/resources/basemap-1.0.5.tar.gz
HDF5 1.8.15 http://uv-cdat.llnl.gov/cdat/resources/hdf5-1.8.15.tar.gz 03cccb5b33dbe975fdcd8ae9dc021f24
NetCDF 4.3.3.1 http://uv-cdat.llnl.gov/cdat/resources/netcdf-4.3.3.1.tar.gz 5c9dad3705a3408d27f696e5b31fb88c
jasper 1.900.1 http://uv-cdat.llnl.gov/cdat/resources/jasper-1.900.1.tgz b5ae85050d034555790a3ccbc2522860
g2clib 1.2.5 http://uv-cdat.llnl.gov/cdat/resources/g2clib-1.2.5.tar.gz f2b7ea610ec723dc269655b68b6bb7db
libcdms 1.0.0 http://uv-cdat.llnl.gov/cdat/resources/libcdms-1.0.0.tar.gz ce71f54616f755d67fbbb6c81ca4fd62
uuid 1.6.2 http://uv-cdat.llnl.gov/cdat/resources/uuid-1.6.2.tar.gz 5db0d43a9022a6ebbbc25337ae28942f
libcf 1.0-beta11 http://uv-cdat.llnl.gov/cdat/resources/libcf-1.0-beta11.tar.gz aba4896eab79d36c7283fc7b75fb16ee
FFI 3.1 http://uv-cdat.llnl.gov/cdat/resources/libffi-3.1.tar.gz f5898b29bbfd70502831a212d9249d10
PYCPARSER 2.13 http://uv-cdat.llnl.gov/cdat/resources/pycparser-2.13.tar.gz e4fe1a2d341b22e25da0d22f034ef32f
CFFI 0.8.2 http://uv-cdat.llnl.gov/cdat/resources/cffi-0.8.2.tar.gz 37fc88c62f40d04e8a18192433f951ec
CRYPTOGRAPHY 0.4 http://uv-cdat.llnl.gov/cdat/resources/cryptography-0.4.tar.gz d1bb13648a12eda2a54653ba113d2e84
PYOPENSSL 0.14 http://uv-cdat.llnl.gov/cdat/resources/pyOpenSSL-0.14.tar.gz 8579ff3a1d858858acfba5f046a4ddf7
MyProxyClient 1.3.0 http://uv-cdat.llnl.gov/cdat/resources/MyProxyClient-1.3.0.tar.gz 829a299157f91f8ff8a6e5bc8ec1c09c
udunits2 2.2.17 http://uv-cdat.llnl.gov/cdat/resources/udunits-2.2.17.tar.gz b81ab8f24125ce18702ab7b3ca4d566f
freetype 2.4.10 http://uv-cdat.llnl.gov/cdat/resources/freetype-2.4.10.tar.gz
FFMPEG 2.7 http://uv-cdat.llnl.gov/cdat/resources/ffmpeg-2.7.tar.gz 3ad0554981faf2c6deef23a1cd4c8c57
VTK 6.3.0 git://github.com/UV-CDAT/VTK.git uvcdat-master
ESMF 6_3_0rp1 http://uv-cdat.llnl.gov/cdat/resources/esmp.ESMF_6_3_0rp1_ESMP_01.tar.bz2 a9be4fb51da1bc1fab027137297c5030
CDAT uvcdat-2.2.0-245-g93321ad N/A
Cython 0.22.1 http://uv-cdat.llnl.gov/cdat/resources/Cython-0.22.1.tar.gz b920f3c81ae767477a342807bf5e68e8
pyflakes 0.8.1 http://uv-cdat.llnl.gov/cdat/resources/pyflakes-0.8.1.tar.gz 905fe91ad14b912807e8fdc2ac2e2c23
pep8 1.5.7 http://uv-cdat.llnl.gov/cdat/resources/pep8-1.5.7.tar.gz f6adbdd69365ecca20513c709f9b7c93
mccabe 0.3.1 http://uv-cdat.llnl.gov/cdat/resources/mccabe-0.3.1.tar.gz 9a1570c470ff5db678cc0c03d5c0c237
flake8 2.4.1 http://uv-cdat.llnl.gov/cdat/resources/flake8-2.4.1.tar.gz ed45d3db81a3b7c88bd63c6e37ca1d65
IPYTHON 3.0.0 http://uv-cdat.llnl.gov/cdat/resources/ipython-3.0.0.tar.gz b3f00f3c0be036fafef3b0b9d663f27e
SCIPY 0.16.0 http://uv-cdat.llnl.gov/cdat/resources/scipy-0.16.0.tar.gz f721ae2746dcbdd923665ba73d0ba3df
sampledata
singledispatch 3.4.0.3 http://uv-cdat.llnl.gov/cdat/resources/singledispatch-3.4.0.3.tar.gz af2fc6a3d6cc5a02d0bf54d909785fcb
UVCMETRICS  git://github.com/UV-CDAT/uvcmetrics.git uvcdat-2.2.0
windspharm
eof2
eofs
windfield
```

**Comment by jypeter** [comment]
@doutriaux1 you got me wrong there. We need of course an easy-to-find list of what's bundled with UV-CDAT, but here I'm thinking about a page listing packages built on top of CDAT (eg vacumm), or people having used CDAT, or something like that

**A way to show that it's not just CDAT developers who use CDAT**, that there is a growing community, blahblah. Remember that you have to attract more new users to get a self-sustaining community. That and a searchable mailing-list and a working askbot. We are getting there!

* vacumm: http://www.ifremer.fr/vacumm/index.html
* Some metrics stuff? https://github.com/gleckler1/pcmdi_metrics
* Any ACME stuff?

And what would be even better would be to reference the papers written with packages built on top of CDAT

Listing some external resources for python+climate could be useful as well. Johnny Lin's pages have several references to CDAT (sometimes with broken links): http://pyaos.johnny-lin.com/.

**Comment by williams13** [comment]
Jy, this sounds like a great idea. Yes, UV-CDAT is used heavily in DOE's ACME project as the primary visualization and analysis tool. There are also other projects that UV-CDAT support under DOE  as well, such as PCMDI, CMIP, AMIP, ESGF, NARCCAP, TECA, and many others. NASA and NOAA also have projects that utilize UV-CDAT.

**Comment by doutriaux1** [comment]
@williams13 they used to have a "powered by Python" logo. Maybe we could create something similar in addition to the page referencing tools using CDAT.

**Comment by williams13** [comment]
Agreed! I will work on this next week.

Best regards,
Dean
