### ISSUE TITLE
Where are the old pages lurking around?

### ISSUE THREAD

**Issue by durack1** [CDAT/cdat.github.io#98]
Hi fellas (@chaosphere2112 @mattben),
It seems a significant cleanup has been undertaken to the old `cdat` webpages, so that links I'd saved such as:
http://pcmdi.github.io/cdat/tutorials/advanced_cdat/comparing_datasets.html
http://pcmdi.github.io/cdat/quick_reference/cdms
http://pcmdi.github.io/cdat/manuals/cdms_v4.0_html/ch2_cdms_4.0.html

Are no longer live - are these pages relocated somewhere you can point me to?

**Comment by chaosphere2112** [comment]
http://uvcdat.llnl.gov/documentation/cdms/cdms_2.html Is this the same as number 3? The other two, I can't say. I'll try and hunt those down today.

**Comment by mattben** [comment]
@durack1 the page is question are from the pcmdi site. Should this issue be a pcmdi site issue? Some of the old cdat site was scrapped and is viewable here http://uv-cdat.github.io/cdat-site/

http://uv-cdat.github.io/cdat-site/cdms.html

**Comment by durack1** [comment]
@mattben @doutriaux1 I think there is a bunch of stuff that should be migrated across to https://uv-cdat.llnl.gov/ for e.g. [taylor diagrams](http://uv-cdat.github.io/cdat-site/taylordiag.html) and a bunch of the items that are only found under the tutorials heading at http://uv-cdat.github.io/cdat-site/

**Comment by doutriaux1** [comment]
@durack1 agreed they need to be translated to jupyter notebooks

**Comment by doutriaux1** [comment]
@durack1 planning on getting to it eventually... Definitely not unitl after the release.

**Comment by durack1** [comment]
@doutriaux1 good to know, I just didn't want this stuff to get lost, closing the issue would suggest to me that it likely will

**Comment by durack1** [comment]
@doutriaux1 with regard to jupyter notebooks, if you provided us a template we could start pushing out these as part of the ongoing PMP works, I know @gleckler1 and @lee1043 would both be keen to go down that path.. And then we could share the load too, we give you pre-prepared notebooks

**Comment by doutriaux1** [comment]
@durack1 Thanks! I will try to do one then as soon as vcs test suite is in repo.

**Comment by durack1** [comment]
@doutriaux1 great, then we can start using your example as a template for future works.. I know that the [taylor diagram demo](http://uv-cdat.github.io/cdat-site/taylordiag.html) in particular will be heavily used

**Comment by doutriaux1** [comment]
i'll do this one then
